FROM osrf/ros:melodic-desktop-full

LABEL maintainer="m3chd09 <m3chd09@protonmail.com>"

RUN apt update && \
    apt install -y sudo build-essential curl cmake git make libv4l-dev libjpeg-dev libgtk-3-dev libusb-dev && \
    apt clean && \
    git clone https://github.com/slightech/MYNT-EYE-D-SDK.git

WORKDIR /MYNT-EYE-D-SDK

RUN sed -i 's/catkin_make/catkin_make_isolated/g' Makefile && \
    bash -c '. /opt/ros/melodic/setup.bash && make init && make all'
